---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "node-hostname.labels" . | nindent 4 }}
  name: {{ include "node-hostname.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "node-hostname.selectorLabels" . | nindent 4 }}
