# Explanation: Add the label 'ci-cd' to a PR if any file within the '.github' folder is changed
ci-cd:
- changed-files:
  - any-glob-to-any-file: '.github/config/*'
  - any-glob-to-any-file: '.github/workflows/*'
helm:
- changed-files:
  - any-glob-to-any-file: 'charts/**'

# charts
node-hostname:
- changed-files:
  - any-glob-to-any-file: 'charts/node-hostname/*'
